### ISSUE TITLE
mmcv incompatibility with mmdetection

### ISSUE THREAD

**Issue by makifozkanoglu** [microsoft/SoftTeacher#104]
I could not find a compatible mmcv-full version that can import MultiScaleDeformableAttention (even if I tried your indicated version) 

```
/cta/users/mehmet/.conda/envs/softteacher/lib/python3.6/site-packages/mmcv/cnn/bricks/transformer.py:27: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module.
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/cta/users/mehmet/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py:27: UserWarning: `MultiScaleDeformableAttention` in MMCV has been moved to `mmcv.ops.multi_scale_deform_attn`, please update your MMCV
  '`MultiScaleDeformableAttention` in MMCV has been moved to '
Traceback (most recent call last):
  File "/cta/users/mehmet/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py", line 23, in <module>
    from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention
  File "/cta/users/mehmet/.conda/envs/softteacher/lib/python3.6/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/cta/users/mehmet/.conda/envs/softteacher/lib/python3.6/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/cta/users/mehmet/.conda/envs/softteacher/lib/python3.6/site-packages/mmcv/utils/ext_loader.py", line 12, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/cta/users/mehmet/.conda/envs/softteacher/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 15, in <module>
    from mmdet.models import build_detector
  File "/cta/users/mehmet/SoftTeacher/thirdparty/mmdetection/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/cta/users/mehmet/SoftTeacher/thirdparty/mmdetection/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/cta/users/mehmet/SoftTeacher/thirdparty/mmdetection/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/cta/users/mehmet/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/__init__.py", line 14, in <module>
    from .transformer import (DetrTransformerDecoder, DetrTransformerDecoderLayer,
  File "/cta/users/mehmet/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py", line 29, in <module>
    from mmcv.cnn.bricks.transformer import MultiScaleDeformableAttention
ImportError: cannot import name 'MultiScaleDeformableAttention'
```

**Comment by makifozkanoglu** [comment]
your makefile also did not work

**Comment by MendelXu** [comment]
Could it relate to https://github.com/open-mmlab/mmdetection3d/issues/438?

**Comment by makifozkanoglu** [comment]
I tried the solution you sent, however, I could not solve

**Comment by MendelXu** [comment]
Are you sure that the PyTorch is able to work in Cuda mode? Could you try to implement a simple case that will use the GPU without `mmcv`.

**Comment by makifozkanoglu** [comment]
Yes Im sure, PyTorch works in cuda mode

**Comment by MendelXu** [comment]
I see..Could you post your python environment and Cuda envoriment here?

**Comment by makifozkanoglu** [comment]
I used two different environment to make my cuda 11.0 compatible with PyTorch. Both did not work

The first :
python -m pip install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html
git clone https://github.com/open-mmlab/mmdetection.git thirdparty/mmdetection
cd thirdparty/mmdetection && git checkout v2.16.0 && python -m pip install -e .

cuda=11.0
python=3.6
torch==1.9.0
torchvision==0.10.0
mmcv-full==1.3.9
wandb
prettytable

The second:
python -m pip install -r requirements.txt -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.0/index.htmlgit clone https://github.com/open-mmlab/mmdetection.git thirdparty/mmdetection
cd thirdparty/mmdetection && git checkout v2.16.0 && python -m pip install -e .

cuda=11.0
python=3.6
torch==1.7.0
torchvision==0.8.0
mmcv-full==1.3.9
wandb
prettytable

**Comment by MendelXu** [comment]
I am unable to reproduce your problem...
Could you try https://github.com/microsoft/SoftTeacher/issues/39#issuecomment-939296639?

**Comment by DaniloAlves1995** [comment]
Hello @makifozkanoglu, I had the same incompatibility problem and I got fix it installing the follows versions:
`!pip install mmcv-full==1.3.16 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10.0/index.html`
