### ISSUE TITLE
Training on custom dataset error: KeyError: 'SemiDataset: "CocoDataset: \'file_name\'"'

### ISSUE THREAD

**Issue by Hayoung93** [microsoft/SoftTeacher#105]
Hi, I've got an error while trying to train on a custom dataset.
After creating `annotation.json` for trainset and testset, I replaced `ann_file` and `img_prefix` of a config file's `sup` and `unsup`.
Also because I'm using a single GPU, I directly executed `tools/train.py` with `--launcher none` option.

The error I received is:
```
Traceback (most recent call last):
  File "/opt/conda/envs/debug/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/workspace/SoftTeacher/thirdparty/mmdetection/mmdet/datasets/custom.py", line 89, in __init__
    self.data_infos = self.load_annotations(self.ann_file)
  File "/workspace/SoftTeacher/thirdparty/mmdetection/mmdet/datasets/coco.py", line 59, in load_annotations
    info['filename'] = info['file_name']
KeyError: 'file_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/debug/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/workspace/SoftTeacher/ssod/datasets/dataset_wrappers.py", line 9, in __init__
    super().__init__([build_dataset(sup), build_dataset(unsup)], **kwargs)
  File "/workspace/SoftTeacher/thirdparty/mmdetection/mmdet/datasets/builder.py", line 80, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/envs/debug/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "CocoDataset: 'file_name'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/debug/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/debug/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/opt/conda/envs/debug/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/envs/debug/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/conda/envs/debug/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/SoftTeacher/tools/train.py", line 200, in <module>
    main()
  File "/workspace/SoftTeacher/tools/train.py", line 175, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/workspace/SoftTeacher/thirdparty/mmdetection/mmdet/datasets/builder.py", line 80, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/envs/debug/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'SemiDataset: "CocoDataset: \'file_name\'"'
```

My annotation for train (used as sup) looks like:
```
{'images': [{'filename': '/data/data/dacon202111/train/train_150360.png', 'height': 576, 'width': 576, 'id': 150360}, {'filename': '/data/data/dacon202111/train/train_114007.png', 'height': 576, 'width': 576, 'id': 114007}, {'filename': '/data/data/dacon202111/train/train_133859.png', 'height': 576, 'width': 576, 'id': 133859}, {'filename': '/data/data/dacon202111/train/train_136591.png', 'height': 576, 'width': 576, 'id': 136591}, {'filename': '/data/data/dacon202111/train/train_108703.png', 'height': 576, 'width': 576, 'id': 108703}, {'filename': '/data/data/dacon202111/train/train_152149.png', 'height': 576, 'width': 576, 'id': 152149}, {'filename': '/data/data/dacon202111/train/train_134621.png', 'height': 576, 'width': 576, 'id': 134621}],
'annotations': [{'iscrowd': 0, 'image_id': 133859, 'bbox': [34.66666666666667, 292.0, 81.33333333333333, 142.66666666666669], 'category_id': 1, 'id': 21696}, {'iscrowd': 0, 'image_id': 133859, 'bbox': [375.33333333333337, 231.99999999999997, 68.66666666666663, 69.33333333333334], 'category_id': 1, 'id': 21697}, {'iscrowd': 0, 'image_id': 136591, 'bbox': [110.54761904761907, 296.42857142857144, 44.04761904761904, 58.333333333333314], 'category_id': 4, 'id': 21698}, {'iscrowd': 0, 'image_id': 108703, 'bbox': [75.90361445783132, 67.7590361445783, 71.68674698795179, 66.26506024096385], 'category_id': 5, 'id': 21699}, {'iscrowd': 0, 'image_id': 108703, 'bbox': [216.2650602409638
3, 71.97590361445782, 106.02409638554215, 141.56626506024097], 'category_id': 5, 'id': 21700}, {'iscrowd': 0, 'image_id': 152149, 'bbox': [168.10179640718565, 467.66467065868267, 116.76646706586826, 68.2634730538922], 'category_id': 5, 'id': 21701}, {'iscrowd': 0, 'image_id': 134621, 'bbox': [240.25974025974025, 290.9090909090909, 125.97402597402598, 90.25974025974028], 'category_id': 1, 'id': 21702}]
'categories': [{'id': 1, 'name': '01_ulcer'}, {'id': 2, 'name': '02_mass'}, {'id': 4, 'name': '04_lymph'}, {'id': 5, 'name': '05_bleeding'}]}
```
and my annotation for test (used as unsup) looks like:
```
{'images': [{'filename': '/data/data/dacon202111/test/test_212912.png', 'heigh
t': 576, 'width': 576, 'id': 212912}, {'filename': '/data/data/dacon202111/test/test_206459.png', 'height': 576, 'width': 576, 'id': 206459}, {'filename': '/data/data/dacon202111/test/test_213976.png', 'height': 576, 'width': 576, 'id': 213976}, {'filename': '/data/data/dacon202111/test/test_205383.png', 'height': 576, 'width': 576, 'id': 205383}, {'filename': '/data/data/dacon202111/test/test_208131.png', 'height': 576, 'width': 576, 'id': 208131}, {'filename': '/data/data/dacon202111/test/test_207387.png', 'height': 576, 'width': 576, 'id': 207387}], 
'annotations': [], 
'categories': []}
```

I can't figure out what's wrong. Can someone help?

**Comment by MendelXu** [comment]
From your log:
```
Traceback (most recent call last):
  File "/opt/conda/envs/debug/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/workspace/SoftTeacher/thirdparty/mmdetection/mmdet/datasets/custom.py", line 89, in __init__
    self.data_infos = self.load_annotations(self.ann_file)
  File "/workspace/SoftTeacher/thirdparty/mmdetection/mmdet/datasets/coco.py", line 59, in load_annotations
    info['filename'] = info['file_name']
KeyError: 'file_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/debug/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/workspace/SoftTeacher/ssod/datasets/dataset_wrappers.py", line 9, in __init__
    super().__init__([build_dataset(sup), build_dataset(unsup)], **kwargs)
  File "/workspace/SoftTeacher/thirdparty/mmdetection/mmdet/datasets/builder.py", line 80, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/envs/debug/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "CocoDataset: 'file_name'"
```
I think it indicates there should be an item named **file_name** in your annotation dictionary.
However, in your annotation, it is **filename**.
```
'images': [{'filename': '/data/data/dacon202111/train/train_150360.png', 'height': 576, 'width': 576, 'id': 150360}, {'filename': '/data/data/dacon202111/train/train_114007.png', 'height': 576, 'width': 576, 'id': 114007}, {'filename': '/data/data/dacon202111/train/train_133859.png', 'height': 576, 'width': 576, 'id': 133859}, {'filename': '/data/data/dacon202111/train/train_136591.png', 'height': 576, 'width': 576, 'id': 136591}, {'filename': '/data/data/dacon202111/train/train_108703.png', 'height': 576, 'width': 576, 'id': 108703}, {'filename': '/data/data/dacon202111/train/train_152149.png', 'height': 576, 'width': 576, 'id': 152149}, {'filename': '/data/data/dacon202111/train/train_134621.png', 'height': 576, 'width': 576, 'id': 134621}],
'annotations': [{'iscrowd': 0, 'image_id': 133859, 'bbox': [34.66666666666667, 292.0, 81.33333333333333, 142.66666666666669], 'category_id': 1, 'id': 21696}, {'iscrowd': 0, 'image_id': 133859, 'bbox': [375.33333333333337, 231.99999999999997, 68.66666666666663, 69.33333333333334], 'category_id': 1, 'id': 21697}, {'iscrowd': 0, 'image_id': 136591, 'bbox': [110.54761904761907, 296.42857142857144, 44.04761904761904, 58.333333333333314], 'category_id': 4, 'id': 21698}, {'iscrowd': 0, 'image_id': 108703, 'bbox': [75.90361445783132, 67.7590361445783, 71.68674698795179, 66.26506024096385], 'category_id': 5, 'id': 21699}, {'iscrowd': 0, 'image_id': 108703, 'bbox': [216.2650602409638
3, 71.97590361445782, 106.02409638554215, 141.56626506024097], 'category_id': 5, 'id': 21700}, {'iscrowd': 0, 'image_id': 152149, 'bbox': [168.10179640718565, 467.66467065868267, 116.76646706586826, 68.2634730538922], 'category_id': 5, 'id': 21701}, {'iscrowd': 0, 'image_id': 134621, 'bbox': [240.25974025974025, 290.9090909090909, 125.97402597402598, 90.25974025974028], 'category_id': 1, 'id': 21702}]
'categories': [{'id': 1, 'name': '01_ulcer'}, {'id': 2, 'name': '02_mass'}, {'id': 4, 'name': '04_lymph'}, {'id': 5, 'name': '05_bleeding'}]}
```

**Comment by Hayoung93** [comment]
OMG thanks, I'll try it!

**Comment by yuan738** [comment]
Hi, sorry for bothering.
How did you solve this problem?
My error is:
```
Traceback (most recent call last):
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmdet/datasets/custom.py", line 89, in __init__
    self.data_infos = self.load_annotations(self.ann_file)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmdet/datasets/coco.py", line 51, in load_annotations
    self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmdet/datasets/api_wrappers/coco_api.py", line 31, in get_cat_ids
    return self.getCatIds(cat_names, sup_names, cat_ids)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/pycocotools/coco.py", line 170, in getCatIds
    cats = self.dataset['categories']
KeyError: 'categories'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/ywz/yuan/SoftTeacher/ssod/datasets/dataset_wrappers.py", line 9, in __init__
    super().__init__([build_dataset(sup), build_dataset(unsup)], **kwargs)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmdet/datasets/builder.py", line 78, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "CocoDataset: 'categories'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 198, in <module>
    main()
  File "tools/train.py", line 173, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmdet/datasets/builder.py", line 78, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'SemiDataset: "CocoDataset: \'categories\'"'

```
thank you!

**Comment by Hayoung93** [comment]
> Hi, sorry for bothering. How did you solve this problem? My error is:
> 
> ```
> Traceback (most recent call last):
>   File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
>     return obj_cls(**args)
>   File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmdet/datasets/custom.py", line 89, in __init__
>     self.data_infos = self.load_annotations(self.ann_file)
>   File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmdet/datasets/coco.py", line 51, in load_annotations
>     self.cat_ids = self.coco.get_cat_ids(cat_names=self.CLASSES)
>   File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmdet/datasets/api_wrappers/coco_api.py", line 31, in get_cat_ids
>     return self.getCatIds(cat_names, sup_names, cat_ids)
>   File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/pycocotools/coco.py", line 170, in getCatIds
>     cats = self.dataset['categories']
> KeyError: 'categories'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
>     return obj_cls(**args)
>   File "/home/ywz/yuan/SoftTeacher/ssod/datasets/dataset_wrappers.py", line 9, in __init__
>     super().__init__([build_dataset(sup), build_dataset(unsup)], **kwargs)
>   File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmdet/datasets/builder.py", line 78, in build_dataset
>     dataset = build_from_cfg(cfg, DATASETS, default_args)
>   File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> KeyError: "CocoDataset: 'categories'"
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tools/train.py", line 198, in <module>
>     main()
>   File "tools/train.py", line 173, in main
>     datasets = [build_dataset(cfg.data.train)]
>   File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmdet/datasets/builder.py", line 78, in build_dataset
>     dataset = build_from_cfg(cfg, DATASETS, default_args)
>   File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> KeyError: 'SemiDataset: "CocoDataset: \'categories\'"'
> ```
> 
> thank you!

Maybe checking your annotation.json and seeing if there exists a "categories" key would help.

**Comment by yuan738** [comment]
thanks!
I checked my unlabeled2017.json but there is not a “categories”.
 So should I add `“categories”:[]` at the end of the file?
thank you very much:)

**Comment by Hayoung93** [comment]
> thanks! I checked my unlabeled2017.json but there is not a “categories”. So should I add `“categories”:[]` at the end of the file? thank you very much:)

Yes, for unlabeled set, I guess.
Your annotation dict must have same structure (same key set) as provided one.

**Comment by yuan738** [comment]
thank you for your help!
I will try it.
