### ISSUE TITLE
assert len(indices) == len(self) AssertionError

### ISSUE THREAD

**Issue by smntjugithub** [microsoft/SoftTeacher#134]
Traceback (most recent call last):
  File "tools/train.py", line 198, in <module>
    main()
  File "tools/train.py", line 193, in main
    meta=meta,
  File "/media/smn/Elements SE/SoftTeacher-main/ssod/apis/train.py", line 206, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/smn/anaconda3/envs/Soft/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 117, in run
    iter_loaders = [IterLoader(x) for x in data_loaders]
  File "/home/smn/anaconda3/envs/Soft/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 117, in <listcomp>
    iter_loaders = [IterLoader(x) for x in data_loaders]
  File "/home/smn/anaconda3/envs/Soft/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 23, in __init__
    self.iter_loader = iter(self._dataloader)
  File "/home/smn/anaconda3/envs/Soft/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/smn/anaconda3/envs/Soft/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/smn/anaconda3/envs/Soft/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/home/smn/anaconda3/envs/Soft/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/home/smn/anaconda3/envs/Soft/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/home/smn/anaconda3/envs/Soft/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/smn/anaconda3/envs/Soft/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 226, in __iter__
    for idx in self.sampler:
  File "/media/smn/Elements SE/SoftTeacher-main/ssod/datasets/samplers/semi_sampler.py", line 187, in __iter__
    assert len(indices) == len(self)
AssertionError

**Comment by MendelXu** [comment]
Maybe you can refer to this link https://github.com/microsoft/SoftTeacher/issues/109#issuecomment-976335577
