### ISSUE TITLE
QUESTIONS OF RUN ON ONE GPU

### ISSUE THREAD

**Issue by yuan738** [microsoft/SoftTeacher#184]
My Preparations:

ubuntu20.04    python3.6    pytorch1.9.0    cuda10.2    mmcv-full1.3.9    mmdet2.16.0    nvidia1660ti

Data:
```
YOUR_DATA/
  coco/
     train2017/
     val2017/
     unlabeled2017/
     annotations/
         image_info_unlabeled2017.json
         instances_train2017.json
         instances_val2017.json
```

I want to train on one gpu , I trted two ways:

1. `bash tools/dist_train.sh configs/soft_teacher/soft_teacher_faster_rcnn_r50_caffe_fpn_coco_full_720k.py 1`

Result:
```
The module torch.distributed.launch is deprecated and going to be removed in future.Migrate to torch.distributed.run
WARNING:torch.distributed.run:--use_env is deprecated and will be removed in future releases.
 Please read local_rank from `os.environ('LOCAL_RANK')` instead.
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : tools/train.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 1
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:29500
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic__x3th_7z/none_wucutly7
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/torch/distributed/elastic/utils/store.py:53: FutureWarning: This is an experimental API and will be changed in future.
  "This is an experimental API and will be changed in future.", FutureWarning
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic__x3th_7z/none_wucutly7/attempt_0/0/error.json
Traceback (most recent call last):
  File "tools/train.py", line 198, in <module>
    main()
  File "tools/train.py", line 96, in main
    cfg = Config.fromfile(args.config)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 316, in fromfile
    use_predefined_variables)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 234, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 234, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 180, in _file2dict
    check_file_exist(filename)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/ywz/yuan/SoftTeacher/thirdparty/mmdetection/configs/_base_/models/faster_rcnn_r50_fpn.py" does not exist
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8601) of binary: /home/ywz/anaconda3/envs/softteacher_1/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic__x3th_7z/none_wucutly7/attempt_1/0/error.json
Traceback (most recent call last):
  File "tools/train.py", line 198, in <module>
    main()
  File "tools/train.py", line 96, in main
    cfg = Config.fromfile(args.config)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 316, in fromfile
    use_predefined_variables)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 234, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 234, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 180, in _file2dict
    check_file_exist(filename)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/ywz/yuan/SoftTeacher/thirdparty/mmdetection/configs/_base_/models/faster_rcnn_r50_fpn.py" does not exist
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8615) of binary: /home/ywz/anaconda3/envs/softteacher_1/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 2/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=2
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic__x3th_7z/none_wucutly7/attempt_2/0/error.json
Traceback (most recent call last):
  File "tools/train.py", line 198, in <module>
    main()
  File "tools/train.py", line 96, in main
    cfg = Config.fromfile(args.config)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 316, in fromfile
    use_predefined_variables)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 234, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 234, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 180, in _file2dict
    check_file_exist(filename)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/ywz/yuan/SoftTeacher/thirdparty/mmdetection/configs/_base_/models/faster_rcnn_r50_fpn.py" does not exist
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8628) of binary: /home/ywz/anaconda3/envs/softteacher_1/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 1/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=3
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic__x3th_7z/none_wucutly7/attempt_3/0/error.json
Traceback (most recent call last):
  File "tools/train.py", line 198, in <module>
    main()
  File "tools/train.py", line 96, in main
    cfg = Config.fromfile(args.config)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 316, in fromfile
    use_predefined_variables)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 234, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 234, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/config.py", line 180, in _file2dict
    check_file_exist(filename)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/ywz/yuan/SoftTeacher/thirdparty/mmdetection/configs/_base_/models/faster_rcnn_r50_fpn.py" does not exist
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 8641) of binary: /home/ywz/anaconda3/envs/softteacher_1/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish
/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/torch/distributed/elastic/utils/store.py:71: FutureWarning: This is an experimental API and will be changed in future.
  "This is an experimental API and will be changed in future.", FutureWarning
INFO:torch.distributed.elastic.agent.server.api:Done waiting for other agents. Elapsed: 0.00030684471130371094 seconds
{"name": "torchelastic.worker.status.FAILED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 0, "group_rank": 0, "worker_id": "8641", "role": "default", "hostname": "ywz738", "state": "FAILED", "total_run_time": 20, "rdzv_backend": "static", "raw_error": "{\"message\": \"<NONE>\"}", "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\", \"local_rank\": [0], \"role_rank\": [0], \"role_world_size\": [1]}", "agent_restarts": 3}}
{"name": "torchelastic.worker.status.SUCCEEDED", "source": "AGENT", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": null, "group_rank": 0, "worker_id": null, "role": "default", "hostname": "ywz738", "state": "SUCCEEDED", "total_run_time": 20, "rdzv_backend": "static", "raw_error": null, "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\"}", "agent_restarts": 3}}
/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:354: UserWarning: 

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE                
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 8641 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/torch/distributed/launch.py", line 173, in <module>
    main()
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/torch/distributed/launch.py", line 169, in main
    run(args)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/torch/distributed/run.py", line 624, in run
    )(*cmd_args)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/ywz/anaconda3/envs/softteacher_1/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
         tools/train.py FAILED         
=======================================
Root Cause:
[0]:
  time: 2022-03-27_15:10:45
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 8641)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************

```

3.when I tried this [https://github.com/microsoft/SoftTeacher/issues/58](url) 

`python tools/train.py configs/baseline/faster_rcnn_r50_caffe_fpn_coco_full_720k.py --gpus 1`

Result:
```
Traceback (most recent call last):
  File "tools/train.py", line 18, in <module>
    from ssod.apis import get_root_logger, set_random_seed, train_detector
ModuleNotFoundError: No module named 'ssod'
```

So, how can I train on the one gpu?
Should I need to change any other parameters？
Thanks for the teaching！

**Comment by chh6936** [comment]
Hello, I have encountered the same problem. How did you solve it？ @[yuan738](https://github.com/yuan738)

**Comment by yuan738** [comment]
yes.
I downloaded the mmdetection from github and changed the file path.
You can try it.
