### ISSUE TITLE
problem about: KeyError: 'loss_cls'

### ISSUE THREAD

**Issue by JayYangSS** [microsoft/SoftTeacher#69]
I use `soft_teacher_faster_rcnn_r50_caffe_fpn_coco_full_720k.py` to start train process, but got KeyError problem, since I don't have `unlabeled2017` , I use `train2017` as labeled data, and use `val2017` as unlabeled data to test the enviroment, is the problem associated with this operation?
```
"2021-10-21T11:21:15+08:00" 2021-10-21 11:21:15,622 - mmdet.ssod - INFO - Iter [2400/720000]	lr: 1.000e-02, eta: 7 days, 1:59:23, time: 0.846, data_time: 0.029, memory: 10432, ema_momentum: 0.9990, sup_loss_rpn_cls: nan, sup_loss_rpn_bbox: nan, sup_loss_cls: nan, sup_acc: 59.1420, sup_loss_bbox: nan, unsup_loss_rpn_cls: nan, unsup_loss_rpn_bbox: nan, unsup_loss_cls: nan, unsup_acc: 72.6390, unsup_loss_bbox: 0.0000, loss: nan
"2021-10-21T11:21:16+08:00" 2021-10-21 11:21:16,471 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:17+08:00" 2021-10-21 11:21:17,431 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:18+08:00" 2021-10-21 11:21:18,085 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:18+08:00" 2021-10-21 11:21:18,875 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:19+08:00" 2021-10-21 11:21:19,708 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:20+08:00" 2021-10-21 11:21:20,523 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:21+08:00" 2021-10-21 11:21:21,371 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:22+08:00" 2021-10-21 11:21:22,261 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:23+08:00" 2021-10-21 11:21:23,183 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:24+08:00" 2021-10-21 11:21:24,159 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:25+08:00" 2021-10-21 11:21:25,089 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:26+08:00" 2021-10-21 11:21:26,074 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:27+08:00" 2021-10-21 11:21:27,022 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:27+08:00" 2021-10-21 11:21:27,721 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:28+08:00" 2021-10-21 11:21:28,629 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:29+08:00" 2021-10-21 11:21:29,480 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:30+08:00" 2021-10-21 11:21:30,250 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:30+08:00" 2021-10-21 11:21:30,997 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:31+08:00" 2021-10-21 11:21:31,885 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:32+08:00" 2021-10-21 11:21:32,697 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:33+08:00" 2021-10-21 11:21:33,555 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:34+08:00" 2021-10-21 11:21:34,504 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:35+08:00" 2021-10-21 11:21:35,409 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:36+08:00" 2021-10-21 11:21:36,270 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:37+08:00" 2021-10-21 11:21:37,181 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:38+08:00" 2021-10-21 11:21:38,194 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:39+08:00" 2021-10-21 11:21:39,072 - mmdet.ssod - WARNING - Check overflow, downscale loss scale to 1
"2021-10-21T11:21:39+08:00" Traceback (most recent call last):
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/tools/train.py", line 198, in <module>
"2021-10-21T11:21:39+08:00"     main()
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/tools/train.py", line 193, in main
"2021-10-21T11:21:39+08:00"     meta=meta,
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/ssod/apis/train.py", line 206, in train_detector
"2021-10-21T11:21:39+08:00"     runner.run(data_loaders, cfg.workflow)
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/thirdparty/mmcv-1.3.9/mmcv/runner/iter_based_runner.py", line 133, in run
"2021-10-21T11:21:39+08:00"     iter_runner(iter_loaders[i], **kwargs)
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/thirdparty/mmcv-1.3.9/mmcv/runner/iter_based_runner.py", line 60, in train
"2021-10-21T11:21:39+08:00"     outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/thirdparty/mmcv-1.3.9/mmcv/parallel/distributed.py", line 53, in train_step
"2021-10-21T11:21:39+08:00"     output = self.module.train_step(*inputs[0], **kwargs[0])
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 238, in train_step
"2021-10-21T11:21:39+08:00"     losses = self(**data)
"2021-10-21T11:21:39+08:00"   File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
"2021-10-21T11:21:39+08:00"     result = self.forward(*input, **kwargs)
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/thirdparty/mmcv-1.3.9/mmcv/runner/fp16_utils.py", line 130, in new_func
"2021-10-21T11:21:39+08:00"     output = old_func(*new_args, **new_kwargs)
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
"2021-10-21T11:21:39+08:00"     return self.forward_train(img, img_metas, **kwargs)
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/ssod/models/soft_teacher.py", line 50, in forward_train
"2021-10-21T11:21:39+08:00"     data_groups["unsup_teacher"], data_groups["unsup_student"]
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/ssod/models/soft_teacher.py", line 77, in foward_unsup_train
"2021-10-21T11:21:39+08:00"     return self.compute_pseudo_label_loss(student_info, teacher_info)
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/ssod/models/soft_teacher.py", line 120, in compute_pseudo_label_loss
"2021-10-21T11:21:39+08:00"     student_info=student_info,
"2021-10-21T11:21:39+08:00"   File "/data1/train_code/SoftTeacher/ssod/models/soft_teacher.py", line 243, in unsup_rcnn_cls_loss
"2021-10-21T11:21:39+08:00"     loss["loss_cls"] = loss["loss_cls"].sum() / max(bbox_targets[1].sum(), 1.0)
"2021-10-21T11:21:39+08:00" KeyError: 'loss_cls'
"2021-10-21T11:21:47+08:00" Traceback (most recent call last):
"2021-10-21T11:21:47+08:00"   File "/usr/local/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"2021-10-21T11:21:47+08:00"     "__main__", mod_spec)
"2021-10-21T11:21:47+08:00"   File "/usr/local/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
"2021-10-21T11:21:47+08:00"     exec(code, run_globals)
"2021-10-21T11:21:47+08:00"   File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
"2021-10-21T11:21:47+08:00"     main()
"2021-10-21T11:21:47+08:00"   File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
"2021-10-21T11:21:47+08:00"     cmd=cmd)
"2021-10-21T11:21:47+08:00" subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', '/data1/train_code/SoftTeacher/tools/train.py', '--local_rank=0', '/data1/train_code/SoftTeacher/configs/exp-test/soft_teacher_faster_rcnn_r50_caffe_fpn_coco_full_720k.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
"2021-10-21T11:21:47+08:00" [INFO] recv error: exit status 1
"2021-10-21T11:21:47+08:00" [ERROR] error happends during process: exit status 1
"2021-10-21T11:21:48+08:00" [INFO] still reserved
"2021-10-21T11:21:48+08:00" [INFO] recv flag (false)
"2021-10-21T11:21:48+08:00" [INFO] sleeping
"2021-10-21T11:22:03+08:00" [ERROR] kill process failed with error: timed out waiting for the condition
```

**Comment by MendelXu** [comment]
I think the config is ok. And as you are facing the NaN issue, there are several things you can try:
- Add `fp16=None` to the end of the config file. This is to switch the training precision  to fp32 and see whether it is an fp16 issue;
- Downscale the learning rate to see whether it is caused by the too large learning rate.
