### ISSUE TITLE
KeyError: 'loss_cls'

### ISSUE THREAD

**Issue by duany049** [microsoft/SoftTeacher#9]
After 300 Iter training, raise "KeyError: 'loss_cls'".

Below is my training information:

wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: wandb: WARNING Invalid choice
wandb: Enter your choice: wandb: WARNING Invalid choice
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'

CondaEnvException: Unable to determine environment

Please re-run this command with one of the following options:

* Provide an environment name via --name or -n
* Re-run this command inside an activated conda environment.

wandb: W&B syncing is set to `offline` in this directory.  Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
=====group sizes is [1755 7042]
=====len of indices is 14660 - offset: 0 - len self 14660
/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
/home/swap/project/SoftTeacher/thirdparty/mmdetection/mmdet/core/anchor/anchor_generator.py:324: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/home/swap/project/SoftTeacher/thirdparty/mmdetection/mmdet/core/anchor/anchor_generator.py:361: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '
2021-09-13 07:35:50,265 - mmcv - INFO - Reducer buckets have been rebuilt in this iteration.
2021-09-13 07:36:05,024 - mmdet.ssod - INFO - Iter [50/14400]	lr: 9.890e-04, eta: 1:18:29, time: 0.328, data_time: 0.021, memory: 3390, ema_momentum: 0.9800, unsup_weight: 4, sup_loss_rpn_cls: 0.4607, sup_loss_rpn_bbox: 0.2644, sup_loss_cls: 1.8000, sup_acc: 74.8359, sup_loss_bbox: 0.3120, unsup_loss_rpn_cls: 1.2687, unsup_loss_rpn_bbox: 0.4132, unsup_loss_cls: 3.9225, unsup_acc: 78.9180, unsup_loss_bbox: 2.3666, loss: 10.8082
2021-09-13 07:36:20,035 - mmdet.ssod - INFO - Iter [100/14400]	lr: 1.988e-03, eta: 1:14:52, time: 0.300, data_time: 0.012, memory: 3390, ema_momentum: 0.9900, unsup_weight: 4, sup_loss_rpn_cls: 0.2892, sup_loss_rpn_bbox: 0.2540, sup_loss_cls: 0.4055, sup_acc: 92.8125, sup_loss_bbox: 0.2864, unsup_loss_rpn_cls: 0.1523, unsup_loss_rpn_bbox: 0.0000, unsup_loss_cls: 0.0626, unsup_acc: 99.9648, unsup_loss_bbox: 0.0114, loss: 1.4615
2021-09-13 07:36:35,185 - mmdet.ssod - INFO - Iter [150/14400]	lr: 2.987e-03, eta: 1:13:43, time: 0.303, data_time: 0.012, memory: 3390, ema_momentum: 0.9933, unsup_weight: 4, sup_loss_rpn_cls: 0.2405, sup_loss_rpn_bbox: 0.2624, sup_loss_cls: 0.3531, sup_acc: 92.7383, sup_loss_bbox: 0.2667, unsup_loss_rpn_cls: 0.1803, unsup_loss_rpn_bbox: 0.0000, unsup_loss_cls: 0.0657, unsup_acc: 100.0000, unsup_loss_bbox: 0.0000, loss: 1.3686
2021-09-13 07:36:51,586 - mmdet.ssod - INFO - Iter [200/14400]	lr: 3.986e-03, eta: 1:14:30, time: 0.328, data_time: 0.012, memory: 3390, ema_momentum: 0.9950, unsup_weight: 4, sup_loss_rpn_cls: 0.3032, sup_loss_rpn_bbox: 0.3015, sup_loss_cls: 0.4180, sup_acc: 92.7266, sup_loss_bbox: 0.2982, unsup_loss_rpn_cls: 0.1778, unsup_loss_rpn_bbox: 0.0000, unsup_loss_cls: 0.0629, unsup_acc: 100.0000, unsup_loss_bbox: 0.0000, loss: 1.5616
2021-09-13 07:37:07,086 - mmdet.ssod - INFO - Iter [250/14400]	lr: 4.985e-03, eta: 1:14:01, time: 0.310, data_time: 0.012, memory: 3390, ema_momentum: 0.9960, unsup_weight: 4, sup_loss_rpn_cls: 0.3210, sup_loss_rpn_bbox: 0.4059, sup_loss_cls: 0.4333, sup_acc: 92.9453, sup_loss_bbox: 0.3436, unsup_loss_rpn_cls: 0.1687, unsup_loss_rpn_bbox: 0.0000, unsup_loss_cls: 0.0740, unsup_acc: 100.0000, unsup_loss_bbox: 0.0000, loss: 1.7465
2021-09-13 07:37:22,497 - mmdet.ssod - INFO - Iter [300/14400]	lr: 5.984e-03, eta: 1:13:32, time: 0.308, data_time: 0.011, memory: 3390, ema_momentum: 0.9967, unsup_weight: 4, sup_loss_rpn_cls: 0.3386, sup_loss_rpn_bbox: 0.4950, sup_loss_cls: 0.3686, sup_acc: 93.9102, sup_loss_bbox: 0.2682, unsup_loss_rpn_cls: 0.1938, unsup_loss_rpn_bbox: 0.0000, unsup_loss_cls: 0.0760, unsup_acc: 100.0000, unsup_loss_bbox: 0.0000, loss: 1.7401
Traceback (most recent call last):
  File "tools/train.py", line 198, in <module>
    main()
  File "tools/train.py", line 193, in main
    meta=meta,
  File "/home/swap/project/SoftTeacher/ssod/apis/train.py", line 205, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 53, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/swap/project/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/swap/project/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/swap/project/SoftTeacher/ssod/models/soft_teacher.py", line 50, in forward_train
    data_groups["unsup_teacher"], data_groups["unsup_student"]
  File "/home/swap/project/SoftTeacher/ssod/models/soft_teacher.py", line 77, in foward_unsup_train
    return self.compute_pseudo_label_loss(student_info, teacher_info)
  File "/home/swap/project/SoftTeacher/ssod/models/soft_teacher.py", line 120, in compute_pseudo_label_loss
    student_info=student_info,
  File "/home/swap/project/SoftTeacher/ssod/models/soft_teacher.py", line 244, in unsup_rcnn_cls_loss
    loss["loss_cls"] = loss["loss_cls"].sum() / max(bbox_targets[1].sum(), 1.0)
KeyError: 'loss_cls'

**Comment by duany049** [comment]
I think it is caused by multiple threads, I has tried change workers_per_gpu from 4 to 0, then there is no problem here!
but loss become nan

**Comment by MendelXu** [comment]
I think it is not related to multiple threads. What about the batch size? Did you use a batch size of 1?

**Comment by duany049** [comment]
> I think it is not related to multiple threads. What about the batch size? Did you use a batch size of 1?

> I think it is not related to multiple threads. What about the batch size? Did you use a batch size of 1?

> I think it is not related to multiple threads. What about the batch size? Did you use a batch size of 1?

Thank you for your reply, samples_per_gpu is 2.

Below is my config:


_base_="base.py"

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=4,
    train=dict(

        sup=dict(

            ann_file="data/coco/annotations/instances_train2017.json",
            img_prefix="data/coco/train2017/",

        ),
        unsup=dict(

            ann_file="data/coco/annotations/instances_unlabeled2017.json",
            img_prefix="data/coco/unlabeled2017/",

        ),
    ),
    sampler=dict(
        train=dict(
            sample_ratio=[1, 1],
        )
    ),
)

semi_wrapper = dict(
    train_cfg=dict(
        unsup_weight=2.0,
    )
)

checkpoint_config = dict(by_epoch=False, interval=1000, max_keep_ckpts=20)
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
# optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# lr_config = dict(step=[2400 * 4, 3200 * 4])
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[1000, 3200 * 4])
runner = dict(_delete_=True, type="IterBasedRunner", max_iters=3600 * 4)

**Comment by MendelXu** [comment]
I see. I will have a try.

**Comment by duany049** [comment]
> I see. How many GPUs do you use? I will have a try.

Only one GPU

**Comment by MendelXu** [comment]
OK. I will post the debug result here ASAP.

**Comment by duany049** [comment]
> OK. I will post the debug result here ASAP.

Thanks

**Comment by MendelXu** [comment]
I can reproduce the `NaN` problem. And I think it is mainly related to the learning rate. In our code, the learning rate (`optimizer=dicr(lr=[HERE})` indicates the total learning rate for a batch. So for a smaller batch, you should reduce the learning rate (maybe 1/32 of the original one in your case).

**Comment by duany049** [comment]
Thank you for your reply. 
I will try a bigger batch size in server.
Can't you repeat "KeyError: 'loss_cls'"?  Maybe it's because I train on a custom dataset

**Comment by MendelXu** [comment]
Yes, I can't. I tried to change the `workers_per_gpu` but can only observe the `nan` error. Could you pull the latest code and run several iterations on coco dataset?

**Comment by duany049** [comment]
> Yes, I can't. I tried to change the `workers_per_gpu` but can only observe the `nan` error. Could you pull the latest code and run several iterations on coco dataset?

I'll try it sometime. I need to download the Coco dataset first

**Comment by duany049** [comment]
> Yes, I can't. I tried to change the `workers_per_gpu` but can only observe the `nan` error. Could you pull the latest code and run several iterations on coco dataset?

After I use bigger batch size on the server, the problem went away.

**Comment by MendelXu** [comment]
OK.

**Comment by wyz0916-gitHub** [comment]
> > Yes, I can't. I tried to change the `workers_per_gpu` but can only observe the `nan` error. Could you pull the latest code and run several iterations on coco dataset?
> 
> After I use bigger batch size on the server, the problem went away.

Hi,I had the same problem, but couldn't solve it.
